driver/LKM/src/util.c
**Summary**
Haven't run test plan. There are still things missing to run the test I think. But since this is a TRIVIAL typo, I'd say it is worth fixing it first without worrying anything.
=> fix typo of "reutrn" => "return"

server/docs/docker-install-zh_CN.md, server/docs/docker-install.md, server/docs/install-zh_CN.md, server/docs/install.md
**Summary**
This PR fix some errors in install docs
In some installation documents, the # symbol appears before the word nohup, which makes it easy to make mistakes.
=> Fix install docs description error

driver/LKM/include/anti_rootkit.h, driver/LKM/src/smith_hook.c
1, NR_syscalls not defined, should include <asm/syscall.h>
2, mm->owner only available with memcg enabled
=> building issues resolved for kernel 3.16

agent/plugin/plugin.go
插件子进程启动的时候会立刻和插件 server 发送 req
server 收到 req 就立即调用插件的 Connect 方法
但这时候可能插件 cmd 里的 Process 还没构建好，随后引发 panic
所以这里建议改为直接用 req 里的 pid
=> fix plugin process is nil

agent/plugin/server.go
调用 plugin sever Close 方法的时候，触发了 Panic
原因分析：
Golang `net` 包中 `Listener` 中的注释
调用 Close 方法后，所有阻塞的 Accept 会返回 Error
当 Listener Close 后，Accept 会不再阻塞，并且不断返回  “use of closed network connection” 错误。
但这里触发异常的主要原因是这时候 conn 对象是 nil ，然而仍旧起了一个 Go 程去解包数据，所以当 io 读取的时候，直接触发了 Panic。
这里建议用一个外部 flag 标记 socket 关闭，并在 socket Close 前赋值，采用外部 flag 标记可以方便处理资源竞态问题。
在 Accept 后判断标记后直接 break
=> fix socket accept panic

driver/LKM/include/util.h, driver/LKM/src/smith_hook.c
get_process_socket() and smith_get_pid_tree() could grab a task_struct
which is being released, i.e. increment task->usage while it's already
zero-valued. The race window is very small.
The solution is: don't increment task->usage if it's already zero to
avoid the race conditions. Any access of task->real_parent also has
the same risk of races, but not fatal, only gets inconsistent data.
**Summary**
Explain …
=> Fix: race upon task->real_parent accessing

driver/LKM/Makefile, driver/LKM/centos_check.sh, driver/LKM/include/kprobe.h, driver/LKM/include/struct_wrap.h, driver/LKM/include/util.h, driver/LKM/src/anti_rootkit.c, driver/LKM/src/smith_hook.c, driver/LKM/src/util.c, driver/LKM/ubuntu_check.sh
Change Logs:
1,  Kernel 5.17 supported: verified with 5.17.0-rc5/5.17.1
2, RISC-V64 supported: verified with VisionFive SBC
3, bugfix in exit_handler:  wrong parameter values
4, ENOENT failures to be ignored for execve events
5, building scripts improved for kernel version handling
=> codes synced to latest mongoose repo

driver/LKM/Makefile
The docker image for CentOS stores headers in /usr/src/kernels
and has no corresponding entries in /lib/modules
=> FIXME: auto-building failed on Jenkins CI

driver/LKM/include/trace.h, driver/LKM/src/trace.c
Building failure due to absence of PDE_DATA:
1) PDE_DATA removed and replaced by pde_data after 5.17
2) only 1 usecase in HIDS: use compiler switch rather macro
=> Kernel 5.17.x support

driver/LKM/src/smith_hook.c
fput() could trigger reschedule or further i/o op, which could
lead severe issues (BUGON) with kernels before 3.6. After 3.6
fput() will do further processing in delayed work or irq work.
=> disable get_process_socket for kernels before 3.6

driver/LKM/Makefile
header-files corrected for pde_data checking of v1.7
The way of header-files locating via 'find' only works for v1.8.
=> correct header-files for pde_data checking

driver/LKM/src/smith_hook.c
Should use P_GET_COMPAT_SYSCALL_NAME, not P_GET_SYSCALL_NAME
Related issue: https://github.com/bytedance/Elkeid/issues/266
=> name corrected for kretprobe of compat_sys_execveat

plugins/collector/container/container.go
**Summary**
This PR fixes the following **bug**:
**Bug detail**
`TrimLeft` returns a slice of the string s with all leading Unicode code points contained in cutset removed.
`TrimPrefix` returns s without the provided leading prefix string. If s doesn't start with prefix, s is returned unchanged.
In conclusion, if the sha256 value begins with `2`, `5` or `6`, Container ImageID and ImageName will be trimed too much not as expected.
```go
package main
import (
"fmt"
"strings"
)
func main() {
fmt.Println(strings.TrimLeft("sha256:620b7f3d1d248633cf84077e6c376dbad6eff5b3510c96fb4550dc896e40e5c4", "sha256:"))
fmt.Println(strings.TrimPrefix("sha256:620b7f3d1d248633cf84077e6c376dbad6eff5b3510c96fb4550dc896e40e5c4", "sha256:"))
}
// Output:
// …
```
=> Fix the string trim errors of Container ImageID and ImageName

driver/LKM/src/init.c, driver/LKM/src/smith_hook.c
Wrong parameters were given to memeset, thus leads gcc compiler skipping memset operation (zeroing skipped).
Kernels < 3.2.6 will be affected, CentOS6 are included.
=> Possible crash caused by uninitialized structures

driver/LKM/src/smith_hook.c
1) return length checking for udp_recvmsg and udpv6_recvmsg: we only care payloads >= 20 bytes
2) code cleaned for kprobe entry and kretprobe handlers of udp_recvmsg & udpv6_recvmsg
=> enhancement for dns resolving

driver/LKM/dkms.conf
**Summary**
This PR fixes/implements the following **features**
Example.
As dkms has been installed ,and kernel-headers & gcc version both matches.
```bash
dkms remove $(dkms status|awk -F ', ' '{print $1}'|grep elkeid-driver) --all || true
git clone  https://github.com/bytedance/Elkeid.git
rm -rf /usr/src/elkeid-driver-* || true
cp -r Elkeid/driver/LKM /usr/src/elkeid-driver-1.7.0.10
rm -rf Elkeid
dkms add -m elkeid-driver -v 1.7.0.10
dkms install -m elkeid-driver -v 1.7.0.10
```
Tests
```bash
modinfo hids_driver
modprobe hids_driver
dmesg | tail
rmmod hids_driver
dmesg | tail
```
KnownErrors
* DKMS will failed if gcc or kernel-headers is mismatch from /proc/version
```text
#mismatch example
gcc version == 4.8.0
kernel == 5.14.4
/proc/version == (gcc 8.5.0)
```
=> add dkms support

driver/LKM/src/init.c, driver/LKM/src/smith_hook.c
nf_register_hooks must be called only once upon nf_hook object, otherwise it would lead dead-loop and thus system hang.
We are using register_pernet_subsys as unified soltuion for all network namespaces, but nf_register_net_hooks is only available kernels >= 4.3.0. nf_register_net_hooks is called per-net, while nf_register_hook is NOT. So we need limit the calling of nf_register_hooks, and the same to it's pair: nf_unregister_hooks.
=> cpu-stuck due to multiple registration of nf_hooks

driver/LKM/include/kprobe_print.h
**Summary**
Bind6 event SaFamily should be 10 not 2
```python
import sys
import socket
import time
local_addr = "::1"
local_port = 12345
sock = socket.socket(family=socket.AF_INET6, proto=socket.IPPROTO_TCP)
try:
sock.bind((local_addr, local_port))
except Exception as err:
pass
time.sleep(3)
try:
sock.close()
except:
pass
```
Try bind any IPv6 address and check the bind event.
Fixes #506
=> fix bind6 SaFamily value

driver/LKM/Makefile, driver/LKM/include/trace.h, driver/LKM/src/trace.c
building issues for openSUSE 42.1 fixed: 
caused by backporting of trace_fs and trace_seq, now check header structures dynamically rather than using kernel versions
=> FIXME: building issue on OpenSUSE 42.1 (4.1.12.1)

rasp/python/python-probe/rasp/smith.py
**Summary**
* [ ✅] Bug 1
https://github.com/bytedance/Elkeid/issues/510
Fixes python staticmethod
=> fix python staticmethod

rasp/librasp/Cargo.toml, rasp/plugin/Cargo.toml
=> fix procfs compile error

driver/LKM/src/smith_hook.c, driver/LKM/src/trace_buffer.c
1,  Network headers files rearranged and <net/ipv6.h> included:
CentOS 6 got building failures due to lack of ipv6_addr_any
2,  IS_ENABLED() used by latest trace_ringbuffer, but not defined
**Summary** …
=> FIXME: building failure for CentOS 6

rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java, rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithLoader.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
=> Fix cloader

agent/plugin/plugin_linux.go
Function Load() could be used to overwrite any files with user-controlled input of plugin name.
Before downloading, must validation the target path and restrict the directory where the plugins are to be stored.
=> FIXME: directory traversal vulnerability in agent codepath

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java, rasp/jvm/JVMProbe/src/main/resources/class.yaml, rasp/python/python-probe/rasp/probe/client/smith_message.cpp, rasp/python/python-probe/rasp/probe/client/smith_message.h, rasp/python/python-probe/rasp/probe/client/smith_probe.cpp, rasp/python/python-probe/rasp/probe/client/smith_probe.h, rasp/python/python-probe/rasp/probe/library.cpp
1.Fix the issue of incorrect PID in the reporting message;
2.Implement automatic fault discovery functionality for cpython using signals
**Summary**
Fixes #
=> automatic fault discovery for cpython

rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/ClassUploadTransformer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageSerializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilter.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilterDeserializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilterSerializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassUpload.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Heartbeat.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Trace.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/TraceDeserializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/TraceSerializer.java
Fix the issue of inconsistent JSON in the reported events caused by using Gson instead of the previous Jackson version
=> Main hupdate guoyj

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Client.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageDecoder.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageEncoder.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageHandler.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageSerializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Operate.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilter.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilterDeserializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilterSerializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Heartbeat.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/SwitchConfig.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Trace.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/TraceDeserializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/TraceSerializer.java, rasp/jvm/JVMProbe/src/main/java/com/security/smith/type/SmithMethod.java, rasp/jvm/JVMProbe/src/main/resources/class.yaml, rasp/librasp/src/comm.rs, rasp/librasp/src/jvm.rs, rasp/librasp/src/manager.rs, rasp/plugin/src/monitor.rs, rasp/plugin/src/operation.rs, rasp/rasp_server/src/comm.rs, rasp/rasp_server/src/proto.rs
add jvm switch
fix message.decode
=> add jvm switch

plugins/lib/rust/.gitignore, plugins/lib/rust/Cargo.toml, plugins/lib/rust/src/lib.rs, plugins/lib/rust/src/sys/mod.rs, plugins/lib/rust/src/sys/unix.rs, plugins/lib/rust/src/sys/windows.rs
=> add windows crash_dump support & sys split

driver/LKM/include/filter.h, driver/LKM/src/filter.c, driver/LKM/src/init.c, driver/LKM/src/smith_hook.c, driver/LKM/src/trace.c
Changelogs:
1, Disable raw tracepoint for performances issues with kernel versions before 5.4.210
2, Add opened instance tracing to improve diagnosis of unknown extra references
=> driver v1.7.0.22 released

driver/LKM/Makefile, driver/LKM/src/smith_hook.c
back to get_user_pages_remote() in case get_arg_page isn't exported by kernel, and we have to handle the variants of get_user_pages_remote, since this function was freqently chagned.
=> FIXME: refuse to load due to lack of get_arg_page()

driver/LKM/Makefile, driver/LKM/src/smith_hook.c
struct file changed by commit 90ee6ed: "fs: port files to file_ref" f_ref (file_ref_t) was introduced to replace f_count
related commit: https://github.com/torvalds/linux/commit/90ee6ed7
=> FIXME: building errors with new kernels after 6.13

driver/LKM/Makefile
'uname -r' used in Makefile scripts to locate header files, then wrong compiler switches generated from old headers are to be used for the new kernel
=> FIXME: dkms failed to build when installing new kernel
