README-zh_CN.md
README.md

Add group email

---

agent/main.go

Close plugin server before exit.

---

driver/LKM/src/smith_hook.c
driver/LKM/src/util.c

task parent -> real_parent

---

driver/LKM/src/smith_hook.c
driver/README-zh_CN.md
driver/README.md

**Summary**
* temporarily close dns hook 
Fixes #

temporarily close dns hook

---

driver/LKM/src/smith_hook.c

**Summary**
* fix connect_syscall_handler warning
Fixes #

fix connect_syscall_handler warning

---

README-zh_CN.md
README.md

add starlink link

---

agent/collector/go.mod
agent/collector/go.sum
agent/collector/main.go

Fix deps of collector.

---

driver/LKM/include/util.h

fix centos8 build error issue

---

driver/LKM/include/anti_rootkit.h
driver/LKM/include/kprobe_print.h
driver/LKM/include/smith_hook.h
driver/LKM/include/trace.h
driver/LKM/include/util.h
driver/LKM/src/anti_rootkit.c
driver/LKM/src/smith_hook.c
driver/LKM/src/trace.c
driver/LKM/src/util.c

Synced to latest release:
1, new kernels (up to 5.12) supported
2, ARM64/AArch64 supported
3, several compiling warnings resolved

merged to latest release

---

driver/LKM/src/filter.c

any commands other than driver-defined will lead memory leaks
**Summary**
Fixes #

FIXME: possible memory leak for unknown commands

---

server/docs/quick-start-zh_CN.md

fix readme file

---

server/manager/biz/hander/v1/agent_config.go
server/manager/biz/hander/v1/agent_task.go

default config set to empty when not set

---

rasp/python/rasp/py2/pyr/hook_socket.py
rasp/python/rasp/py3/pyr/hook_socket.py

fix using void var

---

README-zh_CN.md
README.md

@EBWi11 @whitelez Please review, thx.

update rasp intro in README-zh_CN

---

rasp/Makefile
rasp/librasp/src/golang.rs

add pangolin static build option

---

.gitmodules
rasp/Makefile
rasp/python/python-inject/CMakeLists.txt
rasp/python/python-inject/README.md
rasp/python/python-inject/caller/Makefile
rasp/python/python-inject/caller/main.c
rasp/python/python-inject/main.cpp

add python injector README.md

---

.gitmodules
rasp/Makefile

remove python injector CXXFLAGS

---

rasp/golang/sample/go/CMakeLists.txt

patch golang sample build

---

.github/workflows/Elkeid.yml

add github actions

---

rasp/node/README.md

add node probe README.md

---

agent/scanner/README-zh_CN.md
agent/scanner/README.md

* add build target x86_64-unknown-linux-gnu
**Summary**
This PR fixes/implements the following **missing doc**
* update rustup Compilation Environment Requirements
```bash
#add build target x86_64-unknown-linux-gnu
rustup target add x86_64-unknown-linux-gnu
```
**Test plan (no need)**
Fixes #87

Kulukami patch scanner readme

---

rasp/golang/README.md

update golang usage

---

agent/scanner/README-zh_CN.md
agent/scanner/README.md

**Summary**
This PR fixes the following **doc**
test pre-compiled plugin::scanner binary
sha256 == feae8dfe029571d0e7c6c2e873dd03c8134573a33240aabe1a34be13956b7a45

[update][readme] scanner plugin 

---

agent/scanner/README-zh_CN.md
agent/scanner/README.md

**Summary**
This PR fixes the following **build requirement**
**Ref issues**
Ref #87 #97 #67

[Update][doc] plugin scanner

---

README-zh_CN.md
README.md

fix readme bug

---

driver/LKM/include/util.h
driver/LKM/src/filter.c

fix filter add whitelist bug

---

.github/workflows/Elkeid.yml

add github actions for agent/server

---

driver/LKM/include/trace.h
driver/LKM/include/util.h

fix implicit declaration of function 'isspace' bug

---

server/manager/biz/hander/v1/agent_tags.go

fix AddTags

---

server/manager/biz/hander/v1/agent_task.go

fix createTask UpdateTime

---

driver/LKM/src/anti_rootkit.c

work_func() might re-queue the dealyed work during module unloading
**Summary**
Fixes #

FIXME: possible race upon anti-rootkit worker

---

driver/LKM/include/util.h

building failures resolved.
**Summary**
Fixes #

FIXME: missing declaration of msleep()

---

rasp/INSTALL
rasp/README.md

update musl cdn url

---

driver/LKM/Makefile
driver/LKM/ringbuffer_struct_check.sh

handling of ring-buffer interface changes revised

FIXME: building (on debian) broken

---

.gitmodules
rasp/golang/CMakeLists.txt
rasp/golang/client/smith_client.cpp
rasp/golang/client/smith_client.h
rasp/golang/client/smith_message.cpp
rasp/golang/client/smith_message.h
rasp/golang/client/smith_probe.cpp
rasp/golang/client/smith_probe.h
rasp/golang/go/api/api.h
rasp/golang/go/symbol/func.cpp
rasp/golang/go/symbol/func.h
rasp/golang/go/symbol/line_table.cpp
rasp/golang/loader/elf/loader.h
rasp/golang/main.cpp

golang support rate limit

---

server/manager/biz/hander/v6/asset_center.go

修改资产部分漏洞关联的代码

---

driver/LKM/include/util.h

**Summary**
* [*] Breaking changes
Fixes #

CentOS 8 building failures resolved

---

plugins/collector/process.go
plugins/collector/socket.go

fix collector fields.

---

server/manager/biz/hander/v1/agent_task.go

**Summary**
Fixes #fix manager bug

fix updateConfig bug

---

rasp/jvm/JVMProbe/proguard-rules.pro

keep java processor class

---

driver/LKM/src/smith_hook.c

Too big high threshold caused endless loop of on/off switching,
so kretprobe would be installed right after unloading. Here we
adjusted the thresholds according to the data from production
servers, also unified the judgement conditions to udp rate.

FIXME: high cpu issue with udp_recvmsg kretprobe

---

server/manager/task/agent_subtask.go
server/manager/task/agent_update_subtask.go
server/manager/task/hub_alarm.go
server/manager/task/hub_asset.go
server/manager/task/system_alert.go
server/manager/task/trace_rd.go

fix error format

---

driver/LKM/src/smith_hook.c

The default value (num_possible_cpus()) of maxactive is too small
for a non-preemptable 2-core system. Here we set the minimal value
of maxactive as 32 to avoid possible missings.
**Summary**
Demonstrate the code is solid. Example: The exact commands you ran and their output, …

FIXME: events (59) missing for cron tasks on 2-core KVM guest

---

plugins/scanner/libclamav.sh
plugins/scanner/src/model/engine/clamav/mod.rs

This PR implements the following **features**

1.9/scanner

---

driver/DOC/Description_of_Elkeid's_Crash_caused_by_fput_in_low_version_Kernel.md
driver/README-zh_CN.md
driver/README.md

add Elkeid Driver Doc: <Description of Elkeid's Crash caused by fput in low version Kernel>

Add driver doc

---

.github/workflows/Elkeid.yml
.gitmodules
rasp/docker/Dockerfile
rasp/docker/php.Dockerfile
rasp/php/CMakeLists.txt
rasp/php/README.md
rasp/php/client/smith_client.cpp
rasp/php/client/smith_client.h
rasp/php/client/smith_message.cpp
rasp/php/client/smith_message.h
rasp/php/client/smith_probe.cpp
rasp/php/client/smith_probe.h
rasp/php/cmake/FindPHP.cmake
rasp/php/library.cpp
rasp/php/library.h
rasp/php/php/api.cpp
rasp/php/php/api.h
rasp/php/php/hash.cpp
rasp/php/php/hash.h

add php probe

---

rasp/jvm/JVMProbe/build.gradle

upgrade asm library version to 9.3

---

rasp/librasp/src/golang.rs
rasp/librasp/src/nodejs.rs
rasp/plugin/src/monitor.rs

fix logging && add random interval in report thread

---

rasp/golang/CMakeLists.txt
rasp/php/CMakeLists.txt

fix logger thread terminated abnormally

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Message.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/BlockConfig.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/FilterConfig.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Heartbeat.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/LimitConfig.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/PatchConfig.java

remove UUID deserializer of config message

---

server/manager/distribute/job/manage.go

fix NewCronJobManager init bug

---

server/manager/conf/index.json

subtask token index set unique to false

---

rasp/golang/client/smith_client.cpp
rasp/golang/loader/main.cpp
rasp/golang/main.cpp
rasp/node/injector.js
rasp/node/smith.js

resolve relocation entries in advance

---

rasp/golang/client/smith_probe.cpp
rasp/php/CMakeLists.txt
rasp/php/client/smith_client.cpp
rasp/php/client/smith_message.cpp
rasp/php/client/smith_message.h
rasp/php/client/smith_probe.cpp
rasp/php/library.cpp

hide shared library symbols by default

---

rasp/Makefile
rasp/librasp/src/comm.rs
rasp/librasp/src/settings.rs
rasp/plugin/settings.toml

update jattach; new mount script

---

rasp/librasp/src/manager.rs

parse empty message

---

rasp/librasp/src/main.rs
rasp/librasp/src/runtime.rs

update python filter; fix `process` mode

---

.github/workflows/Elkeid_rasp_release.yml

build rasp on self-hosted runner

---

rasp/INSTALL
rasp/README.md

update documentation of rasp

---

driver/LKM/src/smith_hook.c

Should use inode (path->dentry->d_inode) rather than path.
Related Tracker: https://github.com/bytedance/Elkeid/issues/322

FIXME: IS_PRIVATE called but with wrong parameter (path)

---

rasp/python/python-loader/CMakeLists.txt

update dependencies of python loader

---

rasp/php/library.cpp

add PHP module dependencies

---

rasp/php/library.cpp

support start probe in daemon mode

---

plugins/driver/src/config.rs
plugins/driver/src/kmod.rs
plugins/driver/src/transformer.rs
plugins/driver/src/transformer/cache.rs
plugins/driver/src/utils.rs

feat: update 1.9.1 driver plugin.

---

driver/LKM/src/smith_hook.c

Before 3.2.6 kretprobe could lead memory leaking of kretprobe instances if entry-handler returns non-zero values. This bug was fixed in 3.2.6, and might be backported.
Here we make all entry-handler always return 0 to avoid this possible memory leaking issue for all kernels before 3.2.6.
Tracker: https://github.com/bytedance/Elkeid/issues/339

Workaround for kretprobe bug: instances leaking

---

driver/LKM/src/smith_hook.c

Entry handlers: udp_recvmsg_entry_handler and udpv6_recvmsg_entry_handler would return error codes other than 0 for kernels < 3.2.6.
Both routines are converted and make sure udp_recvmsg_handler wont continue for error cases.

Workaround for possible kretprobe instance leaking

---

.github/workflows/Elkeid_driver_build.yml
.github/workflows/Elkeid_driver_release.yml
driver/build_script/gen_ci_from_dockerfiles.py

update driver CI

---

.github/workflows/Elkeid_driver_build.yml
.github/workflows/Elkeid_driver_release.yml
driver/build_script/gen_ci_from_dockerfiles.py
driver/build_script/x86_64/batch_compile_elrepo7_lt.sh
driver/build_script/x86_64/batch_compile_elrepo7_ml.sh
driver/build_script/x86_64/batch_compile_elrepo8_lt.sh
driver/build_script/x86_64/batch_compile_elrepo8_ml.sh
driver/dockerfiles.x86_64/Dockerfile.rhel7_elrepo_lt
driver/dockerfiles.x86_64/Dockerfile.rhel7_elrepo_ml
driver/dockerfiles.x86_64/Dockerfile.rhel8_elrepo_lt
driver/dockerfiles.x86_64/Dockerfile.rhel8_elrepo_ml

Main gcc ko

---

.github/workflows/Elkeid_driver_build.yml
.github/workflows/Elkeid_driver_release.yml
driver/build_script/aarch64/batch_compile_el7.sh
driver/build_script/gen_ci_from_dockerfiles.py

CI: add docker name arch

---

rasp/jvm/JVMProbe/build.gradle
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Client.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Message.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/log/SmithLogger.java

upgrade dependencies of JVM probe

---

plugins/baseline/config/linux/5000.yaml
plugins/baseline/src/check/analysis.go

baseline add security

---

plugins/baseline/README-zh_CN.md
plugins/baseline/README.md

add baseline english document

---

rasp/php/php/api.h

optimize performance: check quotas before tracking for php probe

---

rasp/golang-ebpf/CMakeLists.txt
rasp/golang-ebpf/client/smith_message.cpp
rasp/golang-ebpf/client/smith_message.h
rasp/golang-ebpf/ebpf/src/config.h
rasp/golang-ebpf/ebpf/src/event.h
rasp/golang-ebpf/ebpf/src/probe.bpf.c
rasp/golang-ebpf/ebpf/src/trace.h
rasp/golang-ebpf/main.cpp

support speed limit for golang eBPF probe

---

README-zh_CN.md
README.md
server/web_console/LICENSE

add Elkeid License

---

rasp/librasp/src/manager.rs
rasp/plugin/settings.toml
rasp/plugin/src/monitor.rs
rasp/plugin/src/operation.rs

random interval settings

---

server/manager/biz/handler/v6/virus_detection.go
server/manager/internal/virus_detection/virus_detection_init.go
server/manager/internal/virus_detection/virus_detection_task.go

切换病毒扫描的任务接口到新接口

---

server/manager/biz/handler/v6/asset_center.go

修复主机列表的批量导出功能

---

rasp/golang-ebpf/CMakeLists.txt
rasp/golang-ebpf/client/smith_client.cpp
rasp/golang-ebpf/client/smith_client.h
rasp/golang-ebpf/main.cpp

update asyncio library for golang eBPF probe

---

rasp/golang-ebpf/CMakeLists.txt
rasp/golang-ebpf/client/smith_client.cpp
rasp/golang-ebpf/main.cpp

optimize persist event for asyncio

---

plugins/baseline/config/linux/1200.yaml
plugins/baseline/config/linux/1300.yaml
plugins/baseline/config/linux/1400.yaml

update baseline config

---

rasp/php/library.cpp
rasp/php/php/api.h

fix bug: start php probe client in process group leader

---

driver/LKM/include/kprobe_print.h
driver/LKM/src/smith_hook.c

psad feature implemented basing on netfilter hooks, could be dynamically turned on or off via module param: /sys/module/hids_driver/parameters/psad_switch

Feature: port-scan attack detection implemented

---

plugins/baseline/README-zh_CN.md
plugins/baseline/README.md

fix readme flie -> file

---

.github/workflows/Elkeid_driver_build.yml
.github/workflows/Elkeid_driver_release.yml
driver/dockerfiles.x86_64/Dockerfile.almalinux8
driver/dockerfiles.x86_64/Dockerfile.almalinux9
driver/dockerfiles.x86_64/Dockerfile.rocky8
driver/dockerfiles.x86_64/Dockerfile.rocky9
driver/dockerfiles.x86_64/Dockerfile.ubuntu1604_hwe
driver/dockerfiles.x86_64/Dockerfile.ubuntu1804_hwe
driver/dockerfiles.x86_64/Dockerfile.ubuntu2004_hwe

Main update ci

---

driver/LKM/src/init.c

version updated to 1.7.0.13

---

driver/LKM/Makefile

Makefile of LKM now unified to v1.8

Compiling failures for Debian 9/10

---

rasp/python/python-probe/rasp/__init__.py
rasp/python/python-probe/rasp/smith.py

fix bug: decorate static function with staticmethod

---

rasp/Makefile
rasp/golang/vcpkg.json
rasp/librasp/src/nodejs.rs
rasp/php/client/smith_probe.cpp
rasp/php/library.cpp
rasp/python/python-probe/rasp/probe/client/smith_probe.cpp

fix bugs of RASP probe

---

rasp/python/python-loader/vcpkg.json

fix python loader depend lib mimalloc

---

rasp/Makefile

Fixes pangolin build that not use vcpkg

Fix python build

---

rasp/Makefile
rasp/librasp/src/comm.rs
rasp/librasp/src/runtime.rs

fix NSMount path
fix attach failed when process not in container
feat jvm version check
* [✅ ] Bug 1

fix mount when process not in container

---

rasp/NSMount/main.cpp
rasp/node/src/schema.js
rasp/node/src/smith.js

**Summary**
fix mount failed when container has process injected
fix nodejs block

fix mount repeat failed and nodejs cannot block

---

rasp/golang-ebpf/client/smith_client.cpp
rasp/golang/client/smith_client.cpp
rasp/golang/client/smith_message.cpp
rasp/php/client/smith_client.cpp
rasp/php/client/smith_message.cpp
rasp/python/python-probe/rasp/probe/client/smith_client.cpp
rasp/python/python-probe/rasp/probe/client/smith_message.cpp

fix go\php\python probe cannot send msg after reconnected
fix probe parse block json

fix probe reconnect send data and block

---

server/manager/internal/baseline/task.go

baseline task bug fix

---

rasp/librasp/src/comm.rs
rasp/php/CMakeLists.txt
rasp/python/python-probe/rasp/probe/CMakeLists.txt

Fix re match

---

rasp/librasp/src/comm.rs

revert mount script

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Client.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageHandler.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Config.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Item.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Json.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Mgr.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Scanner.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilter.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/StackFrame.java

Integrate rule code and the entire process.

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Client.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/MessageHandler.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Config.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Data.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Mgr.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/Rule_Version.java

Add Rule Receive Code

---

.gitignore
rasp/jvm/JVMProbe/src/main/resources/class.yaml

Feat process

---

rasp/librasp/src/golang.rs
rasp/librasp/src/runtime.rs
rasp/plugin/src/report.rs
rasp/plugin/src/utils.rs

feat golang binsize

---

driver/.cargo/config.toml
driver/Cargo.toml
driver/build.rs
driver/src/bin/rst.rs
driver/src/bindings.rs
driver/src/lib.rs

**Summary**
This PR implements the following **features**

update: add libring rust capi binding

---

rasp/NSMount/main.cpp

[ ✅] Feature 
Fixes overlays in k8s and feat devicemapper storage driver

feat overlay and devicemapper storage driver

---

rasp/plugin/src/monitor.rs

feat inject rapid

---

rasp/librasp/src/lib.rs
rasp/rasp_server/src/comm.rs

fix rwlock when send probe message

fix rwlock when send proe message

---

rasp/Makefile

fix zlib 404

---

rasp/librasp/Cargo.toml

add wait-timeout lib

---

rasp/rasp_server/src/comm.rs

fix sock is exist before rasp start and type is directory

fix sock file is exist and is dir

---

rasp/golang-ebpf/client/smith_message.cpp
rasp/golang/client/smith_message.cpp
rasp/node/src/client.js
rasp/php/client/smith_message.cpp
rasp/plugin/src/report.rs
rasp/plugin/src/utils.rs

add probe_version for 2995&2997

---

rasp/jvm/JVMProbe/build.gradle
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java

fix asm lib in jdk21

---

rasp/librasp/src/comm.rs
rasp/librasp/src/manager.rs

[ ✅] Bug 1
fix container escape vulnerability

fix container escape vulnerability

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/asm/SmithClassVisitor.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/asm/SmithMethodVisitor.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/type/SmithMethod.java

add exception hook callback support

---

.gitignore
rasp/jvm/JVMProbe/build.gradle
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/common/SmithHandler.java
rasp/jvm/JVMProbe/src/main/resources/class.yaml

feat memshell init hook

---

rasp/librasp/src/comm.rs
rasp/librasp/src/nodejs.rs
rasp/plugin/settings.toml

fix unix socket,add a new directory as mount directory

feat mount and link uds

---

rasp/plugin/src/monitor.rs

add send message record and errlog

feat message log

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/ClassUploadTransformer.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/SendClassInfo.java
rasp/jvm/JVMProbe/src/main/resources/class.yaml

Rasp feat asmhook guoyj

---

.github/workflows/Elkeid.yml
.github/workflows/Elkeid_driver_build.yml
.github/workflows/Elkeid_driver_release.yml
.github/workflows/Elkeid_plugin_scanner_aarch64.yml
.github/workflows/Elkeid_plugin_scanner_build.yml
.github/workflows/Elkeid_plugin_scanner_x86_64.yml
driver/build_script/x86_64/batch_compile_ol9_uek.sh
driver/dockerfiles.x86_64/Dockerfile.ol9_uek

**Summary**
This PR implements the following **ci**

Main update ci 20240410

---

rasp/librasp/src/comm.rs
rasp/plugin/src/monitor.rs
rasp/rasp_server/src/comm.rs

fix rasp plugin normal exit
fix  link log when pid  not exist

fix rasp plugin normal exit

---

rasp/golang/go/symbol/build_info.cpp

fix go probe crash bescause of .go.buildinfo

---

driver/LKM/src/trace_buffer.c

fix:Invalid number of character '(' when these macros are defined: 'BITS_PER_LONG=32'.

---

driver/LKM/Makefile
driver/LKM/dkms.conf
driver/LKM/include/memcache.h
driver/LKM/include/smith_hook.h
driver/LKM/include/trace.h
driver/LKM/include/util.h
driver/LKM/src/anti_rootkit.c
driver/LKM/src/filter.c
driver/LKM/src/init.c
driver/LKM/src/memcache.c
driver/LKM/src/smith_hook.c
driver/LKM/src/trace.c
driver/LKM/src/trace_buffer.c
driver/LKM/src/util.c

Kernel module v1.7.0.19 released.

Elkeid module v1.7.0.19

---

rasp/librasp/src/comm.rs

fix link error when path not exist

fix link path not exist

---

rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java

Fix cloader

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/Heartbeat.java

feat JVM discard_count

---

plugins/lib/rust/src/lib.rs
rasp/plugin/src/monitor.rs

add send_records_high_priority

add rust plugin high priority pipe

---

rasp/librasp/src/runtime.rs

fix 
https://bugs.openjdk.org/browse/JDK-8222005
https://bugs.openjdk.org/browse/JDK-8292695
and add "+DisableAttachMechanism" check

fix jdk bugs

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java
rasp/jvm/JVMProbe/src/main/resources/class.yaml

Remove the added test code

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/asm/SmithClassVisitor.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/common/SmithHandler.java
rasp/jvm/JVMProbe/src/main/resources/class.yaml

feat Tomcat upgrade 
feat Tomcat executor
fix <init> desc not match when run jsp

feat Tomcat Upgrade/Executor

---

rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/processor/FileDescriptorProcessor.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/processor/ProcessProcessor.java

fix java.lang.ClassCircularityError when combine interfaces and superclass

fix interfaces combine superclass

---

rasp/golang/client/smith_client.cpp
rasp/golang/client/smith_message.cpp
rasp/golang/client/smith_message.h
rasp/golang/client/smith_probe.cpp
rasp/golang/client/smith_probe.h
rasp/golang/go/api/api.h

feat go-probe discard count

---

rasp/node/src/client.js
rasp/node/src/smith.js
rasp/python/python-probe/rasp/probe/client/smith_client.cpp
rasp/python/python-probe/rasp/probe/client/smith_message.cpp
rasp/python/python-probe/rasp/probe/client/smith_message.h
rasp/python/python-probe/rasp/probe/client/smith_probe.cpp
rasp/python/python-probe/rasp/probe/client/smith_probe.h
rasp/python/python-probe/rasp/probe/library.cpp

add python-probe discard count
add node-probe discard count

feat python&node discard count

---

rasp/librasp/src/jvm.rs
rasp/librasp/src/manager.rs
rasp/librasp/src/nodejs.rs
rasp/librasp/src/runtime.rs
rasp/rasp_server/Cargo.toml

check java version when attach
check nodejs version when attach

feat process version check

---

rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassFilter.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/client/message/ClassUpload.java

Main rasp fixupdate

---

driver/build_script/aarch64/batch_compile.sh

aarch64 batch compile bugfix

---

rasp/librasp/src/cpython.rs
rasp/librasp/src/golang.rs
rasp/librasp/src/jvm.rs
rasp/librasp/src/manager.rs
rasp/librasp/src/php.rs
rasp/librasp/src/process.rs
rasp/librasp/src/runtime.rs
rasp/plugin/src/operation.rs

fix smith agent attached repeatly

fix smithagent repeatly attach

---

rasp/Makefile
rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbe.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/asm/SmithMethodVisitor.java

Main jvm benchmark

---

rasp/jvm/JVMAgent/src/main/java/com/security/smithloader/SmithAgent.java
rasp/jvm/JVMProbe/src/main/java/com/security/smith/SmithProbeProxy.java
rasp/jvm/JVMProbe/src/main/resources/class.yaml

Rasp engine fixclassname

---

CODE_OF_CONDUCT.md

It's a small grammar fix. nothing major

Small grammer fix

---

driver/LKM/src/init.c
driver/LKM/src/smith_hook.c

Version 1.7.0.23 to be released
